// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoc/calculate.proto

/*
Package calculator is a generated protocol buffer package.

It is generated from these files:
	protoc/calculate.proto

It has these top-level messages:
	PlusRequest
	PlusResponse
	MinusRequest
	MinusResponse
	MultiplePlusRequest
	DevideRequest
	DevideResponse
*/
package calculator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlusRequest struct {
	Number1 int64 `protobuf:"varint,1,opt,name=number1" json:"number1,omitempty"`
	Number2 int64 `protobuf:"varint,2,opt,name=number2" json:"number2,omitempty"`
}

func (m *PlusRequest) Reset()                    { *m = PlusRequest{} }
func (m *PlusRequest) String() string            { return proto.CompactTextString(m) }
func (*PlusRequest) ProtoMessage()               {}
func (*PlusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PlusRequest) GetNumber1() int64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *PlusRequest) GetNumber2() int64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

type PlusResponse struct {
	Result int64 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *PlusResponse) Reset()                    { *m = PlusResponse{} }
func (m *PlusResponse) String() string            { return proto.CompactTextString(m) }
func (*PlusResponse) ProtoMessage()               {}
func (*PlusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PlusResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MinusRequest struct {
	Number1 int64 `protobuf:"varint,1,opt,name=number1" json:"number1,omitempty"`
	Number2 int64 `protobuf:"varint,2,opt,name=number2" json:"number2,omitempty"`
}

func (m *MinusRequest) Reset()                    { *m = MinusRequest{} }
func (m *MinusRequest) String() string            { return proto.CompactTextString(m) }
func (*MinusRequest) ProtoMessage()               {}
func (*MinusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MinusRequest) GetNumber1() int64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *MinusRequest) GetNumber2() int64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

type MinusResponse struct {
	Result int64 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *MinusResponse) Reset()                    { *m = MinusResponse{} }
func (m *MinusResponse) String() string            { return proto.CompactTextString(m) }
func (*MinusResponse) ProtoMessage()               {}
func (*MinusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MinusResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MultiplePlusRequest struct {
	Number []int64 `protobuf:"varint,1,rep,packed,name=number" json:"number,omitempty"`
}

func (m *MultiplePlusRequest) Reset()                    { *m = MultiplePlusRequest{} }
func (m *MultiplePlusRequest) String() string            { return proto.CompactTextString(m) }
func (*MultiplePlusRequest) ProtoMessage()               {}
func (*MultiplePlusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MultiplePlusRequest) GetNumber() []int64 {
	if m != nil {
		return m.Number
	}
	return nil
}

type DevideRequest struct {
	Number1 int64 `protobuf:"varint,1,opt,name=number1" json:"number1,omitempty"`
	Number2 int64 `protobuf:"varint,2,opt,name=number2" json:"number2,omitempty"`
}

func (m *DevideRequest) Reset()                    { *m = DevideRequest{} }
func (m *DevideRequest) String() string            { return proto.CompactTextString(m) }
func (*DevideRequest) ProtoMessage()               {}
func (*DevideRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DevideRequest) GetNumber1() int64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *DevideRequest) GetNumber2() int64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

type DevideResponse struct {
	Result int64 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *DevideResponse) Reset()                    { *m = DevideResponse{} }
func (m *DevideResponse) String() string            { return proto.CompactTextString(m) }
func (*DevideResponse) ProtoMessage()               {}
func (*DevideResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DevideResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*PlusRequest)(nil), "calculator.PlusRequest")
	proto.RegisterType((*PlusResponse)(nil), "calculator.PlusResponse")
	proto.RegisterType((*MinusRequest)(nil), "calculator.MinusRequest")
	proto.RegisterType((*MinusResponse)(nil), "calculator.MinusResponse")
	proto.RegisterType((*MultiplePlusRequest)(nil), "calculator.MultiplePlusRequest")
	proto.RegisterType((*DevideRequest)(nil), "calculator.DevideRequest")
	proto.RegisterType((*DevideResponse)(nil), "calculator.DevideResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Calculator service

type CalculatorClient interface {
	Plus(ctx context.Context, in *PlusRequest, opts ...grpc.CallOption) (*PlusResponse, error)
	Minus(ctx context.Context, in *MinusRequest, opts ...grpc.CallOption) (*MinusResponse, error)
	MultiplePlus(ctx context.Context, in *MultiplePlusRequest, opts ...grpc.CallOption) (*PlusResponse, error)
	Devide(ctx context.Context, in *DevideRequest, opts ...grpc.CallOption) (*DevideResponse, error)
}

type calculatorClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorClient(cc *grpc.ClientConn) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Plus(ctx context.Context, in *PlusRequest, opts ...grpc.CallOption) (*PlusResponse, error) {
	out := new(PlusResponse)
	err := grpc.Invoke(ctx, "/calculator.calculator/Plus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Minus(ctx context.Context, in *MinusRequest, opts ...grpc.CallOption) (*MinusResponse, error) {
	out := new(MinusResponse)
	err := grpc.Invoke(ctx, "/calculator.calculator/Minus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) MultiplePlus(ctx context.Context, in *MultiplePlusRequest, opts ...grpc.CallOption) (*PlusResponse, error) {
	out := new(PlusResponse)
	err := grpc.Invoke(ctx, "/calculator.calculator/MultiplePlus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Devide(ctx context.Context, in *DevideRequest, opts ...grpc.CallOption) (*DevideResponse, error) {
	out := new(DevideResponse)
	err := grpc.Invoke(ctx, "/calculator.calculator/Devide", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Calculator service

type CalculatorServer interface {
	Plus(context.Context, *PlusRequest) (*PlusResponse, error)
	Minus(context.Context, *MinusRequest) (*MinusResponse, error)
	MultiplePlus(context.Context, *MultiplePlusRequest) (*PlusResponse, error)
	Devide(context.Context, *DevideRequest) (*DevideResponse, error)
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Plus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Plus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.calculator/Plus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Plus(ctx, req.(*PlusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Minus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Minus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.calculator/Minus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Minus(ctx, req.(*MinusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_MultiplePlus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplePlusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).MultiplePlus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.calculator/MultiplePlus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).MultiplePlus(ctx, req.(*MultiplePlusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Devide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Devide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.calculator/Devide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Devide(ctx, req.(*DevideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plus",
			Handler:    _Calculator_Plus_Handler,
		},
		{
			MethodName: "Minus",
			Handler:    _Calculator_Minus_Handler,
		},
		{
			MethodName: "MultiplePlus",
			Handler:    _Calculator_MultiplePlus_Handler,
		},
		{
			MethodName: "Devide",
			Handler:    _Calculator_Devide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/calculate.proto",
}

func init() { proto.RegisterFile("protoc/calculate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x24, 0x2d, 0x04, 0xe9, 0x48, 0x19, 0x1e, 0x52, 0x08, 0x59, 0xa8, 0x3c, 0x40, 0x17, 0x82,
	0x08, 0x23, 0x12, 0x52, 0x81, 0x0d, 0x55, 0x42, 0xfd, 0x83, 0x36, 0xbc, 0x21, 0x92, 0x49, 0x42,
	0x6c, 0xf3, 0x2f, 0xfc, 0x2d, 0x6a, 0x9c, 0x50, 0x47, 0xad, 0xda, 0xa1, 0xe3, 0x7b, 0x77, 0xbe,
	0x3b, 0x9f, 0x8d, 0xb0, 0xaa, 0x4b, 0x5d, 0x66, 0xf7, 0xd9, 0x42, 0x66, 0x46, 0x2e, 0x34, 0x27,
	0xcd, 0x82, 0xd0, 0x2d, 0xca, 0x5a, 0x4c, 0x71, 0xf6, 0x21, 0x8d, 0x9a, 0xf3, 0xb7, 0x61, 0xa5,
	0x29, 0xc2, 0x69, 0x61, 0xbe, 0x96, 0x5c, 0x3f, 0x44, 0xde, 0xd8, 0x9b, 0x0c, 0xe7, 0xdd, 0xb8,
	0x46, 0xd2, 0x68, 0xe0, 0x22, 0xa9, 0xb8, 0x41, 0x60, 0x25, 0x54, 0x55, 0x16, 0x8a, 0x29, 0x84,
	0x5f, 0xb3, 0x32, 0x52, 0xb7, 0x12, 0xed, 0x24, 0x5e, 0x10, 0xcc, 0xf2, 0xe2, 0x30, 0xaf, 0x5b,
	0x8c, 0x5a, 0x8d, 0x3d, 0x66, 0x77, 0xb8, 0x98, 0x19, 0xa9, 0xf3, 0x4a, 0xb2, 0x7b, 0xbf, 0x10,
	0xbe, 0x95, 0x8a, 0xbc, 0xf1, 0x70, 0x45, 0xb7, 0x93, 0x78, 0xc5, 0xe8, 0x8d, 0x7f, 0xf2, 0x4f,
	0x3e, 0x24, 0xdc, 0x04, 0xe7, 0x9d, 0xc8, 0xee, 0x74, 0xe9, 0xef, 0x00, 0xce, 0x23, 0xd0, 0x13,
	0x8e, 0x57, 0x21, 0xe9, 0x32, 0x59, 0x2f, 0x13, 0x27, 0x76, 0x1c, 0x6d, 0x02, 0xd6, 0x41, 0x1c,
	0xd1, 0x33, 0x4e, 0x9a, 0x4a, 0xa8, 0x47, 0x72, 0x9b, 0x8e, 0xaf, 0xb6, 0x20, 0xff, 0xe7, 0xdf,
	0x11, 0xb8, 0x4d, 0xd1, 0x75, 0x8f, 0xbc, 0xd9, 0xe1, 0xce, 0x30, 0x53, 0xf8, 0xb6, 0x02, 0xea,
	0x79, 0xf6, 0xba, 0x8d, 0xe3, 0x6d, 0x50, 0x27, 0xb1, 0xf4, 0x9b, 0x4f, 0xfa, 0xf8, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0x20, 0xd7, 0x97, 0xbe, 0x02, 0x00, 0x00,
}
